email:
  false

env:
  global:
    - secure: "O03J5Ad8X+27TL8XZdwhgUe4r+z9ugcT/3kqHSIRxmNHQXsUtqA5RqIPOLoKdXrrd3OK69tQDSpwuNS6qFY5cVpbfkakbQZiNfRwcLku5227No8CBtMVt9+PqPQJSq+W+VgRZiq2TzCXokEVumNHqVAJZrzG0DzuQ1jW1rWZvGLhj+nZ7DKvwzXjIvFpKoDg2yNNcbaMjrbgq2TWNZL1q2QGIjs9cmeqSlIWYrlgcdHRb3sRGmzBrMOF1yEpToWMPN4N3RiOOb0Z93fuWEUyVdHkAImansWB9kGqU1GVirIltgHy0TD0XVFycRGwcEbeIO1n1RyA4ZVfXWMaNQZ98KJ94pWfCXn0B9pEFqqvs7zIN+euMQ+slX1gL+lm8Pp0HOTs83uHCzHtbsAAZV0Zq9qLQlrdRyd0c1nQOM27gHgfFpI57OtV19dwKmkmEVyom4gZdx+X4MV6jSXrK9oo/G5JZ6Q56nSdbNwf2tKHC3pmNuC7sTaktl8kG0Q/vnMqpDHk9mbVJ/5Gs1kYmbpMVfdBqVu8Dz5dV4Zu+E+jl5otfUy2kRTv3HEFtbdtYny7DU0DHr+QyKpr3YZWtrtRfXIiLZxJjZ8iZE4fhkXfbsoUReBjw+bt01yKzoEx5eytQoNkA4iOTJiqxlG1pCpnl9yzL5t3rp1p6QvAfpXbut4="

cache:
  bundler

language:
  ruby

matrix:
  include:
    - rvm: 2.3.1
    - rvm: 2.3.2
    - rvm: 2.3.3
    - rvm: 2.3.8
    - rvm: 2.4.6
      env: RUBYOPT=--enable-frozen-string-literal USE_FIXED_GEMS=yes
    - rvm: 2.5.5
      env: RUBYOPT=--enable-frozen-string-literal USE_FIXED_GEMS=yes
    - rvm: 2.6.2
      env: RUBYOPT=--enable-frozen-string-literal USE_FIXED_GEMS=yes

before_install:
  - "env -u RUBYOPT gem update --system"
  - "env -u RUBYOPT gem install bundler"

script:
  - bundle exec rake coverage
