email:
  false

dist:
  trusty

git:
  depth:
    false

env:
  global:
    - secure: "efAQDrzw3i6uU2e2tgutgcor3DHdTJvCTbH+ZczeTju7ZtDw6bTJv6kOxgo5TGdwa0qSHPr9FmA76ScuwUyT8iX+IkIFdhZpsTXfMxtF8a+En/Ll2jI4GEmbSAG3B+aqFPYRwpcEgO9wy5SCErYWrh7VEgy2wV35krVmFiq4TI0ER+d2SgLoWcdQbFSq3O/6nrA4hUTgBOVl9UcswbpjejCmMxRPJZzkFRcd7YvvRS//RX4kYJN+TWN1Z40h48yv1ZkmnVC7QeyEiaVHeqYfrwGUPESMW4C648S32xhVe+p3mTW5xHzH3AIHyumysE4cYiJGTMkN1/c/sFEOWpzXbXfAR2E803NwReL+zMF8XHkNid49xfECEuRAvWw5ywOEmJ/ZMoaL5zOuWO2QVEK6gy+5Y9yNOvu7BbaZoqL9lj4Hi3Pu8UbXXv/r6nsI6M9Sqx/5eW9/XmrNgOkk2ooM3ax34hDXT+vqzuqQ/qVImljwQdaQfqF+5d2MZPnbBKQyctYQCNt8BYsZi2ExNK4Fct7ndJM9Cd3zC7s2hKMjerSDJ7jY9vDJig0kQW0ABeDVbwfQ8hBpmLffoTdzr+BsjABdLZD28eI6LDFsfkxfVYCRiyyI3GIGnbQbT62nK8OPBQvTSCDDPJl3trWDS4OYGmZOzZ5nzacV8Z0x86JEv+A="

cache:
  bundler

language:
  ruby

matrix:
  include:
    - rvm: 2.3.8
    - rvm: 2.4.6
      env: RUBYOPT=--enable-frozen-string-literal USE_FIXED_GEMS=yes
    - rvm: 2.5.5
      env: RUBYOPT=--enable-frozen-string-literal USE_FIXED_GEMS=yes
    - rvm: 2.6.3
      env: RUBYOPT=--enable-frozen-string-literal USE_FIXED_GEMS=yes

addons:
  sonarcloud:
    organization:
      rggen
    token:
      secure: "r48aakQnn2yyI81Ebg4j3eL/RpeNTyPrQJsMJCFQyRXquPnNI0Iyc7E6JjLzkNtHo4X9Qz1ZKxRMIumfmr8rqo/rr6qBYIRmMwuszvgV4cpp2/Ba/jOPXyFYkmT/J3rKpsKPRhum2vYvP748ozOdQAnQPRp9UIvWjBUGMNS0IuEuE0nm/CWWsoBzrStYeE0Je+ixayqXKSHtJPNJuPdRKXG/ejtIUrO0rjXQlipmVthEzLWNPSUv4wA2THOtpu6W115Ym4TWEmZKvg76vlhe/u2gvlvNNL7ILI8DaxjfjAFCM3XpBdgmuoXfNKEpNiKoc3Ht1ztbjPutsvJa8yJs5G9/54+sx4fxsJpuG0AkMVmvg8U8GLsmnDZfr95V1tcTN06gzwprbwMxEpqJeZ2n3eyrKBf2SuK1uASFfVzALSSjsTlaYzuIG3os2iVKoVWfWdY/szAWGVkWBwgRsD2pllCqfH9Too3Gsmt0nKuXXminK1QBn1PTJuOpbcvPNYk+gMAawu77XJ0HFI9OG5foRte8FFCKoCzCY0rMXvlOHIkDE0nWz5vNlxz7jbGdYnplD7bpHeru9a7YdtaOUNcU4wFAQa8BxDxN7Ck9AQUuzD//9iGh85FCmsMvIjeqsMNlO+gIoXKI99oZbyNKJAKlZZ5xW3IsawLmXvLVeNEbekA="

before_install:
  - "env -u RUBYOPT gem update --system"
  - "env -u RUBYOPT gem install bundler"

script:
  - bundle exec rake coverage
  - sonar-scanner
